// Generated by prisma-extension-emitter, do not edit
import { Prisma } from '@prisma/client'

declare module '@prisma/client' {
  namespace Prisma {
    interface ClientCreateArgs {
      emit?: boolean
    }
    interface ClientUpdateArgs {
      emit?: boolean
    }
    interface ClientUpsertArgs {
      emit?: boolean
    }
    interface ClientupdateManyArgs {
      emit?: boolean
    }
    interface ClientTypeCreateArgs {
      emit?: boolean
    }
    interface ClientTypeUpdateArgs {
      emit?: boolean
    }
    interface ClientTypeUpsertArgs {
      emit?: boolean
    }
    interface ClientTypeupdateManyArgs {
      emit?: boolean
    }
    interface TodoCreateArgs {
      emit?: boolean
    }
    interface TodoUpdateArgs {
      emit?: boolean
    }
    interface TodoUpsertArgs {
      emit?: boolean
    }
    interface TodoupdateManyArgs {
      emit?: boolean
    }
    interface AppealCreateArgs {
      emit?: boolean
    }
    interface AppealUpdateArgs {
      emit?: boolean
    }
    interface AppealUpsertArgs {
      emit?: boolean
    }
    interface AppealupdateManyArgs {
      emit?: boolean
    }
    interface SaleFeedbackCreateArgs {
      emit?: boolean
    }
    interface SaleFeedbackUpdateArgs {
      emit?: boolean
    }
    interface SaleFeedbackUpsertArgs {
      emit?: boolean
    }
    interface SaleFeedbackupdateManyArgs {
      emit?: boolean
    }
    interface SaleTodoCreateArgs {
      emit?: boolean
    }
    interface SaleTodoUpdateArgs {
      emit?: boolean
    }
    interface SaleTodoUpsertArgs {
      emit?: boolean
    }
    interface SaleTodoupdateManyArgs {
      emit?: boolean
    }
    interface AccessCreateArgs {
      emit?: boolean
    }
    interface AccessUpdateArgs {
      emit?: boolean
    }
    interface AccessUpsertArgs {
      emit?: boolean
    }
    interface AccessupdateManyArgs {
      emit?: boolean
    }
    interface ClientCrmCreateArgs {
      emit?: boolean
    }
    interface ClientCrmUpdateArgs {
      emit?: boolean
    }
    interface ClientCrmUpsertArgs {
      emit?: boolean
    }
    interface ClientCrmupdateManyArgs {
      emit?: boolean
    }
    interface DetailizationCreateArgs {
      emit?: boolean
    }
    interface DetailizationUpdateArgs {
      emit?: boolean
    }
    interface DetailizationUpsertArgs {
      emit?: boolean
    }
    interface DetailizationupdateManyArgs {
      emit?: boolean
    }
    interface PaidCrmCreateArgs {
      emit?: boolean
    }
    interface PaidCrmUpdateArgs {
      emit?: boolean
    }
    interface PaidCrmUpsertArgs {
      emit?: boolean
    }
    interface PaidCrmupdateManyArgs {
      emit?: boolean
    }
    interface DistrictCreateArgs {
      emit?: boolean
    }
    interface DistrictUpdateArgs {
      emit?: boolean
    }
    interface DistrictUpsertArgs {
      emit?: boolean
    }
    interface DistrictupdateManyArgs {
      emit?: boolean
    }
    interface ProductCreateArgs {
      emit?: boolean
    }
    interface ProductUpdateArgs {
      emit?: boolean
    }
    interface ProductUpsertArgs {
      emit?: boolean
    }
    interface ProductupdateManyArgs {
      emit?: boolean
    }
    interface ProductGroupCreateArgs {
      emit?: boolean
    }
    interface ProductGroupUpdateArgs {
      emit?: boolean
    }
    interface ProductGroupUpsertArgs {
      emit?: boolean
    }
    interface ProductGroupupdateManyArgs {
      emit?: boolean
    }
    interface ProductUnitCreateArgs {
      emit?: boolean
    }
    interface ProductUnitUpdateArgs {
      emit?: boolean
    }
    interface ProductUnitUpsertArgs {
      emit?: boolean
    }
    interface ProductUnitupdateManyArgs {
      emit?: boolean
    }
    interface RegionCreateArgs {
      emit?: boolean
    }
    interface RegionUpdateArgs {
      emit?: boolean
    }
    interface RegionUpsertArgs {
      emit?: boolean
    }
    interface RegionupdateManyArgs {
      emit?: boolean
    }
    interface SettingCreateArgs {
      emit?: boolean
    }
    interface SettingUpdateArgs {
      emit?: boolean
    }
    interface SettingUpsertArgs {
      emit?: boolean
    }
    interface SettingupdateManyArgs {
      emit?: boolean
    }
    interface UserCreateArgs {
      emit?: boolean
    }
    interface UserUpdateArgs {
      emit?: boolean
    }
    interface UserUpsertArgs {
      emit?: boolean
    }
    interface UserupdateManyArgs {
      emit?: boolean
    }
    interface ArrivedCreateArgs {
      emit?: boolean
    }
    interface ArrivedUpdateArgs {
      emit?: boolean
    }
    interface ArrivedUpsertArgs {
      emit?: boolean
    }
    interface ArrivedupdateManyArgs {
      emit?: boolean
    }
    interface ArrivedProductCreateArgs {
      emit?: boolean
    }
    interface ArrivedProductUpdateArgs {
      emit?: boolean
    }
    interface ArrivedProductUpsertArgs {
      emit?: boolean
    }
    interface ArrivedProductupdateManyArgs {
      emit?: boolean
    }
    interface PaidSupplierCreateArgs {
      emit?: boolean
    }
    interface PaidSupplierUpdateArgs {
      emit?: boolean
    }
    interface PaidSupplierUpsertArgs {
      emit?: boolean
    }
    interface PaidSupplierupdateManyArgs {
      emit?: boolean
    }
    interface SupplierCreateArgs {
      emit?: boolean
    }
    interface SupplierUpdateArgs {
      emit?: boolean
    }
    interface SupplierUpsertArgs {
      emit?: boolean
    }
    interface SupplierupdateManyArgs {
      emit?: boolean
    }
    interface SaleCreateArgs {
      emit?: boolean
    }
    interface SaleUpdateArgs {
      emit?: boolean
    }
    interface SaleUpsertArgs {
      emit?: boolean
    }
    interface SaleupdateManyArgs {
      emit?: boolean
    }
    interface SaleProductCreateArgs {
      emit?: boolean
    }
    interface SaleProductUpdateArgs {
      emit?: boolean
    }
    interface SaleProductUpsertArgs {
      emit?: boolean
    }
    interface SaleProductupdateManyArgs {
      emit?: boolean
    }
    interface PaidClientCreateArgs {
      emit?: boolean
    }
    interface PaidClientUpdateArgs {
      emit?: boolean
    }
    interface PaidClientUpsertArgs {
      emit?: boolean
    }
    interface PaidClientupdateManyArgs {
      emit?: boolean
    }
    interface PaidServerCreateArgs {
      emit?: boolean
    }
    interface PaidServerUpdateArgs {
      emit?: boolean
    }
    interface PaidServerUpsertArgs {
      emit?: boolean
    }
    interface PaidServerupdateManyArgs {
      emit?: boolean
    }
    interface ServerCreateArgs {
      emit?: boolean
    }
    interface ServerUpdateArgs {
      emit?: boolean
    }
    interface ServerUpsertArgs {
      emit?: boolean
    }
    interface ServerupdateManyArgs {
      emit?: boolean
    }
    interface SubscribeCreateArgs {
      emit?: boolean
    }
    interface SubscribeUpdateArgs {
      emit?: boolean
    }
    interface SubscribeUpsertArgs {
      emit?: boolean
    }
    interface SubscribeupdateManyArgs {
      emit?: boolean
    }
    interface PaymentCreateArgs {
      emit?: boolean
    }
    interface PaymentUpdateArgs {
      emit?: boolean
    }
    interface PaymentUpsertArgs {
      emit?: boolean
    }
    interface PaymentupdateManyArgs {
      emit?: boolean
    }
    interface PaidOtherCreateArgs {
      emit?: boolean
    }
    interface PaidOtherUpdateArgs {
      emit?: boolean
    }
    interface PaidOtherUpsertArgs {
      emit?: boolean
    }
    interface PaidOtherupdateManyArgs {
      emit?: boolean
    }
    interface PaidOtherGroupCreateArgs {
      emit?: boolean
    }
    interface PaidOtherGroupUpdateArgs {
      emit?: boolean
    }
    interface PaidOtherGroupUpsertArgs {
      emit?: boolean
    }
    interface PaidOtherGroupupdateManyArgs {
      emit?: boolean
    }
    interface UserRoleCreateArgs {
      emit?: boolean
    }
    interface UserRoleUpdateArgs {
      emit?: boolean
    }
    interface UserRoleUpsertArgs {
      emit?: boolean
    }
    interface UserRoleupdateManyArgs {
      emit?: boolean
    }
  }
}
